# Generated by Django 4.2.5 on 2023-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vacancy_remove_grade_course_remove_grade_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.CharField(choices=[('Польша', 'Польша'), ('Германия', 'Германия')], max_length=255),
        ),
    ]
