# Generated by Django 4.2.5 on 2023-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vacancy_unique_id_alter_vacancy_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='unique_id',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
