# Generated by Django 4.2.5 on 2023-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_country_person_remove_vacancy_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('Польша', 'Польша'), ('Германия', 'Германия'), ('Литва', 'Литва'), ('Испания', 'Испания'), ('Бельгия', 'Бельгия'), ('Великобритания', 'Великобритания')], max_length=255),
        ),
    ]
